title: "intersiber"
email: intersibercom@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
author: intersiber
paginate: 10
paginate_path: "/sayfa/:num"
disqus: 'intersiber'
locale: tr_tr
lang: tr_tr
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-43255182-11

# Authors
authors:
  intersiber:
    name: intersiber
    display_name: intersiber
    avatar: 'assets/images/intersiber.png'
    email: intersiber@gmail.com
    web: https://intersiber.com/
    twitter: https://twitter.com/intersiber
    description: "intersiber"
  Hakan Torun:
    name: Hakan Torun
    display_name: Hakan Torun
    avatar: 'assets/images/hakan-torun.jpg'
    email: wowthemesnet@gmail.com
    web: https://hakan.io
    twitter: https://twitter.com/onepase
    description: "Hakan Torun"

# Social
social:
  instagram: https://www.instagram.com/intersiber/
  facebook: https://www.facebook.com/intersiber
  twitter: https://twitter.com/intersiber

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives